# Default values for vaulpner
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Vault configuration
vault:
  # Vault server address
  address: "http://localhost:8200"
  # Vault namespace (if using Vault Enterprise)
  namespace: ""
  # Vault authentication method
  authMethod: "token"

# vaulpner configuration
vaulpner:
  # Image configuration
  image:
    repository: ghcr.io/outsideorbit/vaulpner
    tag: "latest"
    pullPolicy: IfNotPresent
  
  # Resource limits and requests
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"
    requests:
      memory: "64Mi"
      cpu: "50m"
  
  # Environment variables
  env:
    # Log level
    RUST_LOG: "info"
    # Additional environment variables
    extra: {}
  
  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

# Kubernetes secret configuration
secret:
  # Secret name for storing Vault root token
  name: "vault-root-token"
  # Secret key name
  key: "root"
  # Secret namespace (defaults to release namespace)
  namespace: ""

# Service account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use
  name: ""

# RBAC configuration
rbac:
  # Specifies whether RBAC resources should be created
  create: true

# Pod configuration
pod:
  # Annotations to add to the pod
  annotations: {}
  # Labels to add to the pod
  labels: {}
  # Node selector
  nodeSelector: {}
  # Tolerations
  tolerations: []
  # Affinity
  affinity: {}

# Service configuration
service:
  # Specifies whether a service should be created
  create: true
  # Service type
  type: ClusterIP
  # Service port
  port: 8200
  # Service annotations
  annotations: {}

# Ingress configuration
ingress:
  # Specifies whether an ingress should be created
  enabled: false
  # Ingress class
  className: ""
  # Ingress annotations
  annotations: {}
  # Ingress hosts
  hosts:
    - host: vault.example.com
      paths:
        - path: /
          pathType: Prefix
  # Ingress TLS configuration
  tls: []

# Monitoring configuration
monitoring:
  # Specifies whether service monitor should be created
  serviceMonitor:
    enabled: false
    # ServiceMonitor labels
    labels: {}
    # ServiceMonitor interval
    interval: 30s
    # ServiceMonitor scrape timeout
    scrapeTimeout: 10s
