---
name: Main CI

on:
  push:
    branches: [main]

jobs:
  semantic-version:
    uses: ./.github/workflows/semantic-version.yml

  build-and-push:
    needs:
      - semantic-version
    uses: ./.github/workflows/build-and-push.yml
    with:
      registry: "ghcr.io"
      image_name: "vaulpner"
      production_tag: "latest"
      debug_tag: "debug"
      push_images: true
      build_production: true
      build_debug: true
      major: ${{ needs.semantic-version.outputs.major }}
      minor: ${{ needs.semantic-version.outputs.minor }}
      patch: ${{ needs.semantic-version.outputs.patch }}
      version: ${{ needs.semantic-version.outputs.version }}
      additional_tag: ""
