---
name: Semantic Version

on:
  workflow_call:
  workflow_dispatch:

jobs:
  semantic-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install and configure python-semantic-release
        run: |
          # Install dependencies in parallel
          (pip install python-semantic-release) &
          (apt-get update && apt-get install -y jq) &
          wait
          # Generate configuration file and modify allow_zero_version inline
          semantic-release generate-config -f json \
            | jq '.semantic_release.allow_zero_version = true' \
          > semantic-release-config.json
      - name: Run semantic-version
        run: |
          semantic-release -vvv --noop -c semantic-release-config.json version >> $GITHUB_STEP_SUMMARY